---
- name: Deploy crawler | Copy migration scripts
  copy:
    src: "../migration"
    dest: "{{ crawler_app_dir }}"
    owner: "{{ crawler_user_username }}"
    group: "{{ crawler_user_username }}"

- name: Deploy crawler | Copy migration configuration
  template:
    src: "migration.conf.j2"
    dest: "{{ migration_config_file }}"
    owner: "{{ crawler_user_username }}"
    group: "{{ crawler_user_username }}"

- name: Deploy crawler | Migrate DB
  shell:
    cmd: "db-migrate --config={{ migration_config_file }}"
