---

crawler_user_home: "/home/{{ crawler_user_username }}"
crawler_app_dir: "/opt/sreality_crawler"
crawler_config_file: "{{ crawler_app_dir }}/src/conf.ini"
migration_config_file: "{{ crawler_app_dir }}/migration/migration.conf"
crawler_migrations_dir: "{{ crawler_app_dir }}/migration"
required_pip_packages:
  - selenium
  - beautifulsoup4
  - simple-db-migrate 
  - mysqlclient 
