---
users:
  - username: ansible
    name: Ansible User
    groups: ['wheel']
    password: "{{ ansible_user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    ssh_key:
      - "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAFqzR74qW6xwDvrfsKRSArsTs8x5lggJdoiGxZoPwRrOA7TTiAWPpRnQxc7D4GdAxFB4Ib15fGYJjXK/dlm+JrRKAEvOZEDe9as+txTjnTR2RjXhKDehm3/Jk00l+ccLB5/ShhxfYLJUP4klG0tpxrjIOxI/zUAEkWBoyGroROJLBXRTA== zdenda@DESKTOP-57CF8IG"

ansible_user: ansible
ansible_user_password: "{{ vault_ansible_user_password }}"
ansible_become_password: "{{ ansible_user_password }}"

mysql_root_home: "root"
mysql_root_password: "{{ vault_root_db_password }}"
mysql_databases:
  - name: sreality
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: sreality
    host: "localhost"
    password: "{{ vault_sreality_db_password }}"
    priv: "sreality.*:ALL"

crawler_user_username: "sreality_crawler"
crawler_user_password: "{{ vault_crawler_user_password }}"
